BÀI 3.1:

In [2]:
import numpy as np

print("NumPy version:", np.__version__)
print("\nNumPy build configuration:")
np.show_config()

NumPy version: 2.3.4

NumPy build configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packa

BÀI 3.2:

In [3]:
# 1.
arr = np.arange(10)
print("arr:", arr)
print("dtype:", arr.dtype)
print("shape:", arr.shape)
print("size:", arr.size)

# 2.
arr_even = arr[arr % 2 == 0]
arr_odd = arr[arr % 2 == 1]
print("arr_even:", arr_even)
print("arr_odd:", arr_odd)

# 3.
arr_update_1 = arr.copy()
arr_update_1[arr_update_1 % 2 == 1] = 100
print("arr_update_1:", arr_update_1)


arr: [0 1 2 3 4 5 6 7 8 9]
dtype: int64
shape: (10,)
size: 10
arr_even: [0 2 4 6 8]
arr_odd: [1 3 5 7 9]
arr_update_1: [  0 100   2 100   4 100   6 100   8 100]


BÀI 3.3:

In [4]:
arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# 1
arr_c = np.intersect1d(arr_a, arr_b)
print("arr_c (unique intersection):", arr_c)

# 2
arr_d = np.setdiff1d(arr_a, arr_b)
print("arr_d (unique in arr_a only):", arr_d)

# 3
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 161])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print("arr_e:", arr_e)
print("arr_f (values 5..10):", arr_f)



arr_c (unique intersection): [2 4]
arr_d (unique in arr_a only): [1 3 5 6]
arr_e: [  2   6   1   9  10   3  27   8   6  25 161]
arr_f (values 5..10): [ 6  9 10  8  6]


BÀI 3.4

In [6]:

# 1. 
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1  
print("1) arr_zeros:", arr_zeros)

# 2. 
arr_h = np.arange(10, 25)  
print("2) arr_h :", arr_h[::-1])

# 3. 
arr_k = np.array((1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0), dtype=int)
arr_1 = arr_k[arr_k != 0]
print("3) arr_1 :", arr_1)

# 4. 
arr_4 = np.append(arr_1, [10, 20])
print("4) arr sau khi thêm 10,20:", arr_4)

# 5. 
arr_5 = np.insert(arr_4, 5, 100)
print("5) arr sau khi thêm phân tử có giá trị là 100 vào index 5:", arr_5)

# 6. 
arr_6 = np.delete(arr_5, [0, 1, 2])
print("6) arr sau khi xóa phần tử ở các index 0,1,2:", arr_6)

1) arr_zeros: [0 0 0 0 1 0 0 0 0 0]
2) arr_h : [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
3) arr_1 : [1 2 8 2 1 3 5]
4) arr sau khi thêm 10,20: [ 1  2  8  2  1  3  5 10 20]
5) arr sau khi thêm phân tử có giá trị là 100 vào index 5: [  1   2   8   2   1 100   3   5  10  20]
6) arr sau khi xóa phần tử ở các index 0,1,2: [  2   1 100   3   5  10  20]


BÀI 3.5:

In [32]:
import re
from pathlib import Path
import numpy as np

def read_numbers_from_file(path):
    text = Path(path).read_text(encoding='utf-8')
    nums = re.findall(r"[-+]?\d*\.?\d+", text)
    return [float(x) for x in nums]

SCRIPT_DIR = Path(__file__).parent if "__file__" in globals() else Path.cwd()
HEIGHTS_FILE = SCRIPT_DIR / "heights_1.txt"
WEIGHTS_FILE = SCRIPT_DIR / "weights_1.txt"

if not HEIGHTS_FILE.exists() or not WEIGHTS_FILE.exists():
    print("Không tìm thấy tập tin heights_1.txt hoặc weights_1.txt ở thư mục của file này:")
    print(f"  {SCRIPT_DIR}")
    print("Vui lòng đặt hai tập tin vào cùng thư mục với file này hoặc chỉnh lại đường dẫn trong mã.")
    raise SystemExit(1)

# 1-2. 
height = read_numbers_from_file(HEIGHTS_FILE)   
weight = read_numbers_from_file(WEIGHTS_FILE)   

arr_height = np.array(height)
arr_weight = np.array(weight)

# 3-4. 
INCH_TO_M = 0.0254
POUND_TO_KG = 0.453592

arr_height_m = arr_height * INCH_TO_M
arr_weight_kg = arr_weight * POUND_TO_KG

n_height = arr_height.size
n_weight = arr_weight.size
n_common = min(n_height, n_weight)

# 5. 
if n_common > 0:
    arr_bmi = arr_weight_kg[:n_common] / (arr_height_m[:n_common] ** 2)
else:
    arr_bmi = np.array([])

# 6. 
idx = 50
if idx < arr_weight_kg.size:
    weight_idx50_kg = arr_weight_kg[idx]
else:
    weight_idx50_kg = None

# 7. 
start, end = 100, 110
if start < arr_height_m.size:
    end_index = min(end, arr_height_m.size - 1)
    arr_height_m_100 = arr_height_m[start:end_index + 1]
else:
    arr_height_m_100 = np.array([])

# 8. 
low_bmi_indices = np.where(arr_bmi < 21)[0]
low_bmi_values = arr_bmi[low_bmi_indices]

# 9. 
mean_height_m = arr_height_m.mean() if n_height > 0 else None
mean_weight_kg = arr_weight_kg.mean() if n_weight > 0 else None

# 10. 
max_height_m = arr_height_m.max() if n_height > 0 else None
max_weight_kg = arr_weight_kg.max() if n_weight > 0 else None

# 11. 
min_height_m = arr_height_m.min() if n_height > 0 else None
min_weight_kg = arr_weight_kg.min() if n_weight > 0 else None

print(f"Số lượng bản ghi height = {arr_height.size}, weight = {arr_weight.size}")
print()
print("arr_height (inches) -> arr_height_m (m):")
print(f"  Ví dụ 10 phần tử đầu: {arr_height_m[:10]}")
print()
print("arr_weight (pounds) -> arr_weight_kg (kg):")
print(f"  Ví dụ 10 phần tử đầu: {arr_weight_kg[:10]}")
print()
print(f"arr_bmi (ví dụ 10 đầu): {arr_bmi[:10]}")
print()
if weight_idx50_kg is not None:
    print(f"Cân nặng tại index {idx} = {weight_idx50_kg:.3f} kg")
else:
    print(f"Index {idx} vượt quá kích thước mảng (size={arr_weight_kg.size})")
print()
print(f"arr_height_m[{start}:{end}] (bao gồm {end}):")
print(arr_height_m_100)
print()
print(f"Số cầu thủ có BMI < 21: {low_bmi_indices.size}")
print("Chỉ số (index) và BMI của những người này (tối đa 50 hiển thị):")
for i, b in zip(low_bmi_indices[:50], low_bmi_values[:50]):
    print(f"  index={i}, BMI={b:.3f}")
print()
if mean_height_m is not None:
    print(f"Chiều cao trung bình: {mean_height_m:.3f} m")
else:
    print("Chiều cao trung bình: không có dữ liệu")
if mean_weight_kg is not None:
    print(f"Cân nặng trung bình: {mean_weight_kg:.3f} kg")
else:
    print("Cân nặng trung bình: không có dữ liệu")
print()
if max_height_m is not None:
    print(f"Chiều cao lớn nhất: {max_height_m:.3f} m")
else:
    print("Chiều cao lớn nhất: không có dữ liệu")
if max_weight_kg is not None:
    print(f"Cân nặng lớn nhất: {max_weight_kg:.3f} kg")
else:
    print("Cân nặng lớn nhất: không có dữ liệu")
print()
if min_height_m is not None:
    print(f"Chiều cao nhỏ nhất: {min_height_m:.3f} m")
else:
    print("Chiều cao nhỏ nhất: không có dữ liệu")
if min_weight_kg is not None:
    print(f"Cân nặng nhỏ nhất: {min_weight_kg:.3f} kg")
else:
    print("Cân nặng nhỏ nhất: không có dữ liệu")

Số lượng bản ghi height = 4, weight = 4

arr_height (inches) -> arr_height_m (m):
  Ví dụ 10 phần tử đầu: [4.318  4.3434 4.3688 4.3942]

arr_weight (pounds) -> arr_weight_kg (kg):
  Ví dụ 10 phần tử đầu: [27.21552  26.761928 27.669112 28.122704]

arr_bmi (ví dụ 10 đầu): [1.45965884 1.41859278 1.44967582 1.45645623]

Index 50 vượt quá kích thước mảng (size=4)

arr_height_m[100:110] (bao gồm 110):
[]

Số cầu thủ có BMI < 21: 4
Chỉ số (index) và BMI của những người này (tối đa 50 hiển thị):
  index=0, BMI=1.460
  index=1, BMI=1.419
  index=2, BMI=1.450
  index=3, BMI=1.456

Chiều cao trung bình: 4.356 m
Cân nặng trung bình: 27.442 kg

Chiều cao lớn nhất: 4.394 m
Cân nặng lớn nhất: 28.123 kg

Chiều cao nhỏ nhất: 4.318 m
Cân nặng nhỏ nhất: 26.762 kg


BÀI 3.6:

In [13]:
import numpy as np


def main():
    # 1.
    arr_true = np.ones((3, 3), dtype=bool)
    print("1) arr_true:\n", arr_true, "\n")

    # 2. 
    arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
    arr_2D = arr_1D.reshape(3, 3)
    arr_swap_cols = arr_2D.copy()
    arr_swap_cols[:, [0, 2]] = arr_swap_cols[:, [2, 0]]
    print("2) arr_2D ban đầu:\n", arr_2D)
    print("   sau khi đổi cột 1 <-> 3:\n", arr_swap_cols, "\n")

    # 3. 
    arr_swap_rows = arr_swap_cols.copy()
    arr_swap_rows[[0, 1], :] = arr_swap_rows[[1, 0], :]
    print("3) sau khi đổi dòng 1 <-> 2:\n", arr_swap_rows, "\n")

    # 4. 
    arr_flip_rows = arr_swap_rows[::-1, :]
    print("4) sau khi đảo ngược các dòng:\n", arr_flip_rows, "\n")

    # 5. 
    arr_flip_cols = arr_flip_rows[:, ::-1]
    print("5) sau khi đảo ngược các cột:\n", arr_flip_cols, "\n")

    # 6. 
    arr_2D_null = np.array([
        [1, 2, 3],
        [np.nan, 5, 6],
        [7, np.nan, 9],
        [4, 5, 6]
    ], dtype=float)
    has_nan = np.isnan(arr_2D_null).any()
    print("6) arr_2D_null:\n", arr_2D_null)
    print("   Có giá trị rỗng (NaN)?", has_nan, "\n")

    # 7. 
    arr_no_nan = np.nan_to_num(arr_2D_null, nan=0.0)
    print("7) arr_2D_null sau khi thay NaN bằng 0:\n", arr_no_nan)

if __name__ == "__main__":
    main()

1) arr_true:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

2) arr_2D ban đầu:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
   sau khi đổi cột 1 <-> 3:
 [[2 1 0]
 [5 4 3]
 [8 7 6]] 

3) sau khi đổi dòng 1 <-> 2:
 [[5 4 3]
 [2 1 0]
 [8 7 6]] 

4) sau khi đảo ngược các dòng:
 [[8 7 6]
 [2 1 0]
 [5 4 3]] 

5) sau khi đảo ngược các cột:
 [[6 7 8]
 [0 1 2]
 [3 4 5]] 

6) arr_2D_null:
 [[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
   Có giá trị rỗng (NaN)? True 

7) arr_2D_null sau khi thay NaN bằng 0:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]


BÀI 3.7:

In [28]:
import numpy as np
from pathlib import Path


filepath = Path("baseball_2D.txt")

# 1
baseball = []
if not filepath.exists():
    raise SystemExit(f"Không tìm thấy tập tin: {filepath}")

with filepath.open("r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        try:
            row = [float(p) for p in parts]
        except ValueError:
            continue
        baseball.append(row)

if len(baseball) == 0:
    raise SystemExit("Danh sách 'baseball' rỗng sau khi đọc file.")

# 2
np_baseball = np.array(baseball)

print("Kiểu dữ liệu np_baseball:", np_baseball.dtype)
print("Kích thước np_baseball (rows, cols):", np_baseball.shape)

# 3
idx_50 = 49
if np_baseball.shape[0] > idx_50:
    print("Dòng thứ 50 (1-based, index 49):", np_baseball[idx_50])
else:
    print(f"Không có dòng thứ 50. Số dòng hiện có: {np_baseball.shape[0]}")

# 4
if np_baseball.shape[1] < 2:
    raise SystemExit("Dữ liệu không có đủ cột (cần ít nhất 2 cột: chiều cao, cân nặng).")
np_weight = np_baseball[:, 1]
print("np_weight (một vài giá trị):", np_weight[:5])

# 5
idx_124 = 123
if np_baseball.shape[0] > idx_124:
    height_124 = np_baseball[idx_124, 0]
    print(f"Chiều cao vận động viên thứ 124 (inch): {height_124}")
else:
    print(f"Không có vận động viên thứ 124. Số dòng hiện có: {np_baseball.shape[0]}")

# 6
mean_height = np.mean(np_baseball[:, 0])
mean_weight = np.mean(np_weight)
print(f"Chiều cao trung bình (inch): {mean_height:.2f}")
print(f"Cân nặng trung bình (pounds): {mean_weight:.2f}")

# 7
if np_baseball.shape[0] >= 2:
    corr = np.corrcoef(np_baseball[:, 0], np_weight)[0, 1]
    print(f"Hệ số tương quan Pearson (height vs weight): {corr:.4f}")

    if abs(corr) < 0.1:
        conclusion = "Không có mối tương quan rõ rệt giữa chiều cao và cân nặng."
    elif corr > 0:
        conclusion = "Có tương quan thuận: chiều cao tăng kèm theo cân nặng tăng."
    else:
        conclusion = "Có tương quan nghịch: chiều cao tăng kèm theo cân nặng giảm."
    print("Nhận xét:", conclusion)
else:
    print("Không đủ dữ liệu để tính tương quan.")

Kiểu dữ liệu np_baseball: float64
Kích thước np_baseball (rows, cols): (5, 2)
Không có dòng thứ 50. Số dòng hiện có: 5
np_weight (một vài giá trị): [60. 61. 62. 62. 63.]
Không có vận động viên thứ 124. Số dòng hiện có: 5
Chiều cao trung bình (inch): 172.00
Cân nặng trung bình (pounds): 61.60
Hệ số tương quan Pearson (height vs weight): 0.9707
Nhận xét: Có tương quan thuận: chiều cao tăng kèm theo cân nặng tăng.


BÀI 3.8:

In [33]:
from pathlib import Path

heights_path = Path("heights.txt")
positions_path = Path("positions.txt")

def read_lines(path):
    if not path.exists():
        sample_heights = ["180", "175", "190", "185"]
        sample_positions = ["GK", "M", "A", "D"]
        if path.name == "heights.txt":
            path.write_text("\n".join(sample_heights), encoding="utf-8")
            print(f"{path} không tồn tại: tạo tệp mẫu với {len(sample_heights)} giá trị.")
        elif path.name == "positions.txt":
            path.write_text("\n".join(sample_positions), encoding="utf-8")
            print(f"{path} không tồn tại: tạo tệp mẫu với {len(sample_positions)} giá trị.")
        else:
            raise FileNotFoundError(f"Không tìm thấy {path}")
    with path.open("r", encoding="utf-8") as f:
        return [ln.strip() for ln in f if ln.strip()]

heights = [float(x) for x in read_lines(heights_path)]
positions = [x for x in read_lines(positions_path)]

if len(heights) != len(positions):
    raise ValueError("Số lượng heights và positions không bằng nhau")

# 1.a)
np_positions = np.array(positions)
print("np_positions dtype:", np_positions.dtype)

# 1.b)
np_heights = np.array(heights)
print("np_heights dtype:", np_heights.dtype)

# 2) 
mask_gk = np_positions == "GK"
if mask_gk.any():
    mean_gk = np_heights[mask_gk].mean()
    print("Chiều cao trung bình của GK:", mean_gk)
else:
    print("Không có GK trong dữ liệu")

# 3) 
mask_not_gk = ~mask_gk
if mask_not_gk.any():
    mean_not_gk = np_heights[mask_not_gk].mean()
    print("Chiều cao trung bình của các vị trí khác:", mean_not_gk)
else:
    print("Không có vị trí khác ngoài GK trong dữ liệu")

# 4) 
dtype_players = np.dtype([("position", "U3"), ("height", "f8")])
players = np.zeros(len(heights), dtype=dtype_players)
players["position"] = np_positions
players["height"] = np_heights

print("players dtype:", players.dtype)
print("players (chỉ vài phần tử nếu nhiều):")
print(players[:10])

# 5) 
players_sorted = np.sort(players, order="height")
lowest = players_sorted[0]
highest = players_sorted[-1]
print("Chiều cao thấp nhất:", lowest["height"], "vị trí:", lowest["position"])
print("Chiều cao cao nhất:", highest["height"], "vị trí:", highest["position"])

np_positions dtype: <U16
np_heights dtype: float64
Không có GK trong dữ liệu
Chiều cao trung bình của các vị trí khác: 2.5
players dtype: [('position', '<U3'), ('height', '<f8')]
players (chỉ vài phần tử nếu nhiều):
[("'GK", 1.) ("'M'", 2.) ("'A'", 3.) ("'D'", 4.)]
Chiều cao thấp nhất: 1.0 vị trí: 'GK
Chiều cao cao nhất: 4.0 vị trí: 'D'


BÀI 3.10:

In [36]:
import numpy as np

def to_array(vals):
    arr = np.array([v if v is not None else np.nan for v in vals], dtype=float)
    return arr

def describe_with_numpy(vals):
    arr = to_array([v for v in vals])  # vals có thể chứa None
    if np.isnan(arr).all():
        return {"count":0,"mean":None,"std":None,"min":None,"25%":None,"50%":None,"75%":None,"max":None}
    cnt = int(np.count_nonzero(~np.isnan(arr)))
    mean = float(np.nanmean(arr))
    std = float(np.nanstd(arr, ddof=1)) if cnt > 1 else float("nan")
    mn = float(np.nanmin(arr))
    p25, p50, p75 = [float(x) for x in np.nanpercentile(arr, [25,50,75])]
    mx = float(np.nanmax(arr))
    return {"count":cnt,"mean":mean,"std":std,"min":mn,"25%":p25,"50%":p50,"75%":p75,"max":mx}

# Ví dụ dùng cho mỗi continent:
# Provide an example `items` list (each element is a tuple like (group_key, record_dict))
# Replace this with your actual grouped data when available.
items = [
    ("Europe", {"wine_servings": 50}),
    ("Asia", {"wine_servings": None}),
    ("Africa", {"wine_servings": 10})
]

vals = [it[1].get("wine_servings") for it in items]  # items từ group
print(describe_with_numpy(vals))

{'count': 2, 'mean': 30.0, 'std': 28.284271247461902, 'min': 10.0, '25%': 20.0, '50%': 30.0, '75%': 40.0, 'max': 50.0}


BÀI 3.11:

In [39]:
import csv
import os
from datetime import datetime
from collections import defaultdict
from statistics import mean
import numpy as np

# Utility converters
def to_float(s):
    if s is None or s == '':
        return None
    try:
        return float(s)
    except Exception:
        return None

def to_int(s):
    if s is None or s == '':
        return None
    try:
        return int(float(s))
    except Exception:
        return None

def try_parse_date(s):
    if s is None or s == '':
        return None
    fmts = [
        "%Y-%m-%d",
        "%Y-%m-%d %H:%M:%S",
        "%d/%m/%Y",
        "%m/%d/%Y",
        "%Y/%m/%d",
        "%Y.%m.%d",
    ]
    for f in fmts:
        try:
            return datetime.strptime(s, f)
        except Exception:
            continue
    try:
        return datetime.fromisoformat(s)
    except Exception:
        return None

# Read CSV with trial delimiters (for companies candidates like .esv)
def read_csv_try(path, delimiters=[',', '\t', ';']):
    for d in delimiters:
        with open(path, newline='', encoding='utf-8') as f:
            f.seek(0)
            reader = csv.reader(f, delimiter=d)
            rows = list(reader)
            if not rows:
                continue
            if len(rows[0]) > 1:
                with open(path, newline='', encoding='utf-8') as f2:
                    return list(csv.DictReader(f2, delimiter=d))
    with open(path, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def read_companies(path_dir='.'):
    candidates = ['companies.csv', 'companies.esv', 'companies.tsv']
    for fn in candidates:
        p = os.path.join(path_dir, fn)
        if os.path.exists(p):
            return read_csv_try(p)
    raise FileNotFoundError("companies file not found. Expected companies.csv or companies.esv in current folder.")

# Pretty prints
def head(rows, n=5):
    return rows[:n]

def tail(rows, n=5):
    return rows[-n:] if len(rows) >= n else rows

def print_rows(rows, n=None):
    if not rows:
        print("(empty)")
        return
    cols = list(rows[0].keys())
    print(", ".join(cols))
    rows_iter = rows if n is None else rows[:n]
    for r in rows_iter:
        print(", ".join((str(r.get(c, "")) for c in cols)))

def infer_dtypes(rows):
    if not rows:
        return {}
    cols = list(rows[0].keys())
    dtypes = {}
    for c in cols:
        vals = [r.get(c, "") for r in rows]
        non_null = [v for v in vals if v not in (None, "")]
        if not non_null:
            dtypes[c] = "object"
            continue
        ok_int = True
        for v in non_null:
            try:
                int(float(v))
            except Exception:
                ok_int = False
                break
        if ok_int:
            dtypes[c] = "int"
            continue
        ok_float = True
        for v in non_null:
            try:
                float(v)
            except Exception:
                ok_float = False
                break
        if ok_float:
            dtypes[c] = "float"
            continue
        ok_date = True
        for v in non_null:
            if try_parse_date(v) is None:
                ok_date = False
                break
        if ok_date:
            dtypes[c] = "datetime"
            continue
        dtypes[c] = "object"
    return dtypes

def info(rows):
    if not rows:
        print("Empty dataframe")
        return
    cols = list(rows[0].keys())
    print(f"Rows: {len(rows)}, Columns: {len(cols)}")
    dtypes = infer_dtypes(rows)
    for c in cols:
        vals = [r.get(c, "") for r in rows]
        non_null = sum(1 for v in vals if v not in (None, ""))
        print(f"{c}: non-null={non_null}, dtype={dtypes.get(c,'object')}")

# Replace nulls in stocks1 according to rules (high -> max high per symbol, low -> min low per symbol)
def fill_high_low_by_symbol(rows):
    if not rows:
        return rows
    # group indices by symbol
    groups = defaultdict(list)
    for i, r in enumerate(rows):
        sym = r.get('symbol', '')
        groups[sym].append(i)
    for sym, idxs in groups.items():
        highs = np.array([np.nan if to_float(rows[i].get('high')) is None else to_float(rows[i].get('high')) for i in idxs], dtype=float)
        lows  = np.array([np.nan if to_float(rows[i].get('low')) is None else to_float(rows[i].get('low')) for i in idxs], dtype=float)
        # compute replacements if possible
        max_high = None
        if not np.all(np.isnan(highs)):
            max_high = float(np.nanmax(highs))
        min_low = None
        if not np.all(np.isnan(lows)):
            min_low = float(np.nanmin(lows))
        # apply
        for i in idxs:
            if rows[i].get('high') in (None, ''):
                rows[i]['high'] = "" if max_high is None else str(max_high)
            if rows[i].get('low') in (None, ''):
                rows[i]['low'] = "" if min_low is None else str(min_low)
    return rows

# Concatenate two lists of dicts (stocks)
def concat_rows(a, b):
    return list(a) + list(b)

# Merge stocks with companies: try match company where company['name'] == stock['symbol'] or company['symbol'] == stock['symbol']
def merge_stocks_companies(stocks, companies):
    if not stocks:
        return []
    if not companies:
        # just return stocks with no company fields
        return [dict(r) for r in stocks]
    # build lookup for companies by candidate keys
    comp_map = {}
    for c in companies:
        # prefer explicit keys
        for key in ('symbol', 'name'):
            if key in c and c.get(key) not in (None, ''):
                comp_map.setdefault(str(c.get(key)), []).append(c)
    merged = []
    for s in stocks:
        key = str(s.get('symbol', ''))
        matched = comp_map.get(key, [])
        if matched:
            # if multiple companies match take first
            company = matched[0]
            # merge without overwriting stock's keys
            merged_row = dict(company)  # start with company so we can keep those fields
            merged_row.update(s)        # put stock fields (stock fields win)
            merged.append(merged_row)
        else:
            m = dict(s)
            # add empty company fields
            for col in companies[0].keys():
                if col not in m:
                    m[col] = ""
            merged.append(m)
    return merged

# Aggregations per company using numpy
def agg_per_company(stocks, numeric_cols=('open','high','low','close','volume')):
    groups = defaultdict(list)
    for r in stocks:
        groups[r.get('symbol','')].append(r)
    results = {}
    for sym, rows in groups.items():
        arrs = {}
        for c in numeric_cols:
            vals = np.array([np.nan if to_float(r.get(c)) is None else to_float(r.get(c)) for r in rows], dtype=float)
            arrs[c] = vals
        res = {}
        for c in numeric_cols:
            vals = arrs[c]
            res[c+'_mean'] = None if np.all(np.isnan(vals)) else float(np.nanmean(vals))
        results[sym] = res
    return results

def close_stats_per_company(stocks):
    groups = defaultdict(list)
    for r in stocks:
        groups[r.get('symbol','')].append(r)
    results = {}
    for sym, rows in groups.items():
        closes = np.array([np.nan if to_float(r.get('close')) is None else to_float(r.get('close')) for r in rows], dtype=float)
        if np.all(np.isnan(closes)):
            results[sym] = {'close_mean': None, 'close_max': None, 'close_min': None}
        else:
            results[sym] = {
                'close_mean': float(np.nanmean(closes)),
                'close_max': float(np.nanmax(closes)),
                'close_min': float(np.nanmin(closes)),
            }
    return results

def add_parsed_time(stocks_companies, src_col='date', dest_col='parsed_time'):
    for r in stocks_companies:
        dt = try_parse_date(r.get(src_col))
        r[dest_col] = dt
    return stocks_companies

def add_result_column(stocks_companies):
    for r in stocks_companies:
        o = to_float(r.get('open'))
        c = to_float(r.get('close'))
        if o is None or c is None:
            r['result'] = ''
        else:
            r['result'] = 'up' if c > o else 'down'
    return stocks_companies

if __name__ == '__main__':
    cwd = os.getcwd()
    # paths
    s1_path = os.path.join(cwd, 'stocks1.csv')
    s2_path = os.path.join(cwd, 'stocks2.csv')
    # read stocks1
    if os.path.exists(s1_path):
        stocks1 = read_csv_try(s1_path)
        print("stocks1 head:")
        print_rows(head(stocks1, 5))
        print("stocks1 tail:")
        print_rows(tail(stocks1, 5))
        print("stocks1 dtypes/info:")
        info(stocks1)
    else:
        print("stocks1.csv not found in", cwd)
        stocks1 = []
    # read stocks2
    if os.path.exists(s2_path):
        stocks2 = read_csv_try(s2_path)
        print("stocks2 head:")
        print_rows(head(stocks2, 5))
        print("stocks2 tail:")
        print_rows(tail(stocks2, 5))
        print("stocks2 dtypes/info:")
        info(stocks2)
    else:
        print("stocks2.csv not found in", cwd)
        stocks2 = []
    # read companies
    try:
        companies = read_companies(cwd)
        print("companies sample:")
        print_rows(head(companies, 5))
        print("companies dtypes/info:")
        info(companies)
    except FileNotFoundError as e:
        print(e)
        companies = []

    # 2. check nulls in stocks1 and fill
    if stocks1:
        # check nulls
        any_null = any(any(v in (None, '') for v in r.values()) for r in stocks1)
        print("stocks1 has nulls:", any_null)
        stocks1 = fill_high_low_by_symbol(stocks1)
        print("After filling high/low in stocks1 (head):")
        print_rows(head(stocks1, 5))
    # 3. concat stocks
    stocks = concat_rows(stocks1, stocks2)
    print("stocks combined tail (15):")
    print_rows(tail(stocks, 15))
    # 4. merge stocks and companies
    stocks_companies = merge_stocks_companies(stocks, companies) if stocks else []
    print("stocks_companies head (5):")
    print_rows(head(stocks_companies, 5))
    # 5. average prices and volume per company
    aggs = agg_per_company(stocks)
    print("Average open/high/low/close/volume per company (symbol -> dict):")
    for k, v in aggs.items():
        print(k, v)
    # 6. close stats per company
    closes = close_stats_per_company(stocks)
    print("Close mean/max/min per company:")
    for k, v in closes.items():
        print(k, v)
    # 7. add parsed_time
    stocks_companies = add_parsed_time(stocks_companies, src_col='date', dest_col='parsed_time')
    if stocks_companies:
        print("Type of parsed_time column:", type(stocks_companies[0].get('parsed_time')))
        print_rows(head(stocks_companies, 5))
    # 8. add result column
    stocks_companies = add_result_column(stocks_companies)
    print("stocks_companies with result (head 5):")
    print_rows(head(stocks_companies, 5))

stocks1 head:
(empty)
stocks1 tail:
(empty)
stocks1 dtypes/info:
Empty dataframe
stocks2 head:
(empty)
stocks2 tail:
(empty)
stocks2 dtypes/info:
Empty dataframe
companies sample:
(empty)
companies dtypes/info:
Empty dataframe
stocks combined tail (15):
(empty)
stocks_companies head (5):
(empty)
Average open/high/low/close/volume per company (symbol -> dict):
Close mean/max/min per company:
stocks_companies with result (head 5):
(empty)
